### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/base/Preconditions

### ISSUE THREAD

**Issue by chslover** [Lukaszpg/jPUBG#1]
java.lang.NoClassDefFoundError: com/google/common/base/Preconditions

.. api key not valid ? or .. NoClassDefFoundError ?

**Comment by Lukaszpg** [comment]
Hello! Which version are you using - standalone or maven? I'll check the issue.

**Comment by chslover** [comment]
hello 

jpubg version. 1.3.1 
maven.

**Comment by Lukaszpg** [comment]
Can you please switch to newest version (1.3.5) and tell me if the bug is still occuring?

**Comment by chslover** [comment]
1.3.5 can't import JPubg, JPubgFactory

**Comment by chslover** [comment]
It seems to be a Maven configuration issue. sorry
