### ISSUE TITLE
GET by Steam ID returning string instead of object.

### ISSUE THREAD

**Issue by teanz** [Lukaszpg/jPUBG#2]
Thought this was an issue with pubgtracker (might still be) but I contacted them letting them know that when an API call was made to get player by steamID it would return their websites markup instead of an object. They advised it was fixed. JPubg still collects the markup instead of the Json object. If I make the call using a RESTclient I can obtain the Json object just fine so thinking there's something a bit off in the wrapper.

Looking at the Json returned by the tracking site, I'm assuming the wrapper obtains the players nickname then preforms another lookup using the GET for nickname? Is that correct?

**Comment by Lukaszpg** [comment]
Hello, 

I'll have a look into it. Thanks for your report.

**Comment by teanz** [comment]
Odd, if I make a request using my REST client it spits back the JSON but only if the request header is correct other wise it spits back the HTML. Whats being sent along in the header from the wrappers request?

**Comment by Lukaszpg** [comment]
Here's a request I made in Postman under Chrome. Link: https://imgur.com/a/JYP7Y

Everything seems valid from my side and yet I get bad response. Maybe you'll see something that is off here.

About your question - the only header that is added to the request besides the token is USER_AGENT_TYPE, which is "Mozilla/5.0".

**Comment by teanz** [comment]
Hmmm well I could get the request in wiztools (consistently) while postman worked intermittently. Thing I did note is your passing the steamID but not as its 64bit number which def wont work but even when I use the wrapper to submit a request using the number it returns the markup.

Screens of successful calls = https://imgur.com/a/yUWVd

**Comment by teanz** [comment]
Hey Lukaz,

Figured out what was happening they way I obtain steamIDs to check stats was not returning the original steamID but an instance of it. Figured a way around that and all is well.

Cheers.
